config/routes.rb
ExchangeRates::Application.routes.draw do
  get "home/index"

  resources :exchange_rates

  get "exchange_rate/index"

  root :to => "home#index"

end

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base
  attr_accessible :destination_currency, :rate, :source_currency, :when
  
  validates :destination_currency, :presence => true, :length => { :is => 3 }
  validates :rate,  :presence => true
  validates :source_currency,  :presence => true,  :length => { :is => 3 }
  validates :when,  :presence => true
  
  def self.at(date, source, destination)
    ExchangeRate.where(:when => date,
                       :source_currency => source,
                       :destination_currency => destination).first.rate
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exchange_rates_controller.rb
class ExchangeRatesController < ApplicationController
  # GET /exchange_rates
  # GET /exchange_rates.json
  def index
    @exchange_rates = ExchangeRate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exchange_rates }
    end
  end

  # GET /exchange_rates/1
  # GET /exchange_rates/1.json
  def show
    @exchange_rate = ExchangeRate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exchange_rate }
    end
  end

  # GET /exchange_rates/new
  # GET /exchange_rates/new.json
  def new
    @exchange_rate = ExchangeRate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exchange_rate }
    end
  end

  # GET /exchange_rates/1/edit
  def edit
    @exchange_rate = ExchangeRate.find(params[:id])
  end

  # POST /exchange_rates
  # POST /exchange_rates.json
  def create
    @exchange_rate = ExchangeRate.new(params[:exchange_rate])

    respond_to do |format|
      if @exchange_rate.save
        format.html { redirect_to @exchange_rate, notice: 'Exchange rate was successfully created.' }
        format.json { render json: @exchange_rate, status: :created, location: @exchange_rate }
      else
        format.html { render action: "new" }
        format.json { render json: @exchange_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exchange_rates/1
  # PUT /exchange_rates/1.json
  def update
    @exchange_rate = ExchangeRate.find(params[:id])

    respond_to do |format|
      if @exchange_rate.update_attributes(params[:exchange_rate])
        format.html { redirect_to @exchange_rate, notice: 'Exchange rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exchange_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchange_rates/1
  # DELETE /exchange_rates/1.json
  def destroy
    @exchange_rate = ExchangeRate.find(params[:id])
    @exchange_rate.destroy

    respond_to do |format|
      format.html { redirect_to exchange_rates_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if request.post?
      @when = params[:when]
      @source_currency = params[:source_currency]
      @destination_currency = params[:destination_currency]
      @rate = ExchangeRate.at(@when, @source_currency, @destination_currency)
      
      @amount = params[:amount]                   
      @result = "#{@amount} #{@source_currency} => #{@rate*@amount.to_f} #{@destination_currency}"  
    end
    
    @source_currencies = ExchangeRate.uniq.pluck(:source_currency)
    @destination_currencies = ExchangeRate.uniq.pluck(:destination_currency)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchange_rate_helper.rb
module ExchangeRateHelper
end

app/helpers/exchange_rates_helper.rb
module ExchangeRatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/exchange_rates/_form.html.erb
<%= form_for(@exchange_rate) do |f| %>
  <% if @exchange_rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange_rate.errors.count, "error") %> prohibited this exchange_rate from being saved:</h2>

      <ul>
      <% @exchange_rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :when %><br />
    <%= f.date_select :when %>
  </div>
  <div class="field">
    <%= f.label :source_currency %><br />
    <%= f.text_field :source_currency %>
  </div>
  <div class="field">
    <%= f.label :destination_currency %><br />
    <%= f.text_field :destination_currency %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.text_field :rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exchange_rates/edit.html.erb
<h1>Editing exchange_rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @exchange_rate %> |
<%= link_to 'Back', exchange_rates_path %>

app/views/exchange_rates/index.html.erb
<h1>Listing exchange_rates</h1>

<table>
  <tr>
    <th>When</th>
    <th>Source currency</th>
    <th>Destination currency</th>
    <th>Rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exchange_rates.each do |exchange_rate| %>
  <tr>
    <td><%= exchange_rate.when %></td>
    <td><%= exchange_rate.source_currency %></td>
    <td><%= exchange_rate.destination_currency %></td>
    <td><%= exchange_rate.rate %></td>
    <td><%= link_to 'Show', exchange_rate %></td>
    <td><%= link_to 'Edit', edit_exchange_rate_path(exchange_rate) %></td>
    <td><%= link_to 'Destroy', exchange_rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exchange rate', new_exchange_rate_path %>

app/views/exchange_rates/new.html.erb
<h1>New exchange_rate</h1>

<%= render 'form' %>

<%= link_to 'Back', exchange_rates_path %>

app/views/exchange_rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>When:</b>
  <%= @exchange_rate.when %>
</p>

<p>
  <b>Source currency:</b>
  <%= @exchange_rate.source_currency %>
</p>

<p>
  <b>Destination currency:</b>
  <%= @exchange_rate.destination_currency %>
</p>

<p>
  <b>Rate:</b>
  <%= @exchange_rate.rate %>
</p>


<%= link_to 'Edit', edit_exchange_rate_path(@exchange_rate) %> |
<%= link_to 'Back', exchange_rates_path %>

app/views/home/index.html.erb
<h1>FX-u-like</h1>
<%= link_to "Exchange Rates", exchange_rates_path %>


<form method="post" action=".">
    <p>
        <label>Date:</label> <input type="date" name="when">
    </p>
    <p>
        <label>Amount:</label> <input type="number" name="amount" min="1">    
    </p>
    <p>
        <label>From:</label>
        <select name="source_currency">
            <% @source_currencies.each do |currency| %>
            <option value="<%= currency %>"><%= currency %></option>
            <% end %>
        </select>    
    </p>
    <p>
        <label>To:</label>
        <select name="destination_currency">
            <% @destination_currencies.each do |currency| %>
            <option value="<%= currency %>"><%= currency %></option>
            <% end %>
        </select>    
    </p>
    <input type="submit" />
</form>

<%= @result %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExchangeRates</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #EEEEEE;">

<%= yield %>

</body>
</html>